version: '3'
services:
  test_task_local_postgres:
    container_name: 'test_task_local_postgres'
    image: 'postgres'
    restart: always
    env_file:
      - .env
    ports:
      - '8532:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_task_local
    volumes:
      - /home/docker_data/test-task/db-data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-initdb.d

  test_task_local_redis:
    container_name: 'test_task_local_redis'
    image: redis:latest
    restart: always
    ports:
      - '6579:6379'

  test_task_local_migration:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: test_task_local_migration
    depends_on:
      - test_task_local_postgres
    command: sh -c "pnpm migration:run "

  test_task_local_app:
    env_file:
      - ./.env
    container_name: test_task_local_app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    depends_on:
      - test_task_local_postgres
      - test_task_local_migration
      - test_task_local_redis
