name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: 

 lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: [14.x]
      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js 14
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
      - run: npm install
      - name: Check linting
      - run: npm run test:e2e

  build:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/Rupikz/test-task-nestjs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "production"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
      - name: test_task_local_postgres
        run: |
          docker-compose -f ./docker-compose.yml up --build -d test_task_local_postgres
          
      - name: test_task_local_redis
        run: |
          docker-compose -f ./docker-compose.yml up --build -d test_task_local_redis

      - name: test_task_local_migration
        run: |
          docker-compose -f ./docker-compose.yml up --build -d test_task_local_migration

      - name: test_task_local_app
        run: |
          docker-compose -f ./docker-compose.yml up --build -d test_task_local_app
